
package me.folixa.ws.events;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEventsWS", targetNamespace = "http://webservices.events.folixa.me/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IEventsWS {


    /**
     * 
     * @param img
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadImage", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.UploadImage")
    @ResponseWrapper(localName = "uploadImageResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.UploadImageResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/uploadImageRequest", output = "http://webservices.events.folixa.me/IEventsWS/uploadImageResponse")
    public boolean uploadImage(
        @WebParam(name = "img", targetNamespace = "")
        Image img);

    /**
     * 
     * @param eventsId
     * @param name
     * @param alt
     * @param url
     * @return
     *     returns boolean
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createImage", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.CreateImage")
    @ResponseWrapper(localName = "createImageResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.CreateImageResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/createImageRequest", output = "http://webservices.events.folixa.me/IEventsWS/createImageResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/createImage/Fault/DatabaseException")
    })
    public boolean createImage(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "url", targetNamespace = "")
        String url,
        @WebParam(name = "alt", targetNamespace = "")
        String alt,
        @WebParam(name = "eventsId", targetNamespace = "")
        int eventsId)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param longDescription
     * @param validated
     * @param endDate
     * @param name
     * @param place
     * @param shortDescription
     * @param categoryId
     * @param startDate
     * @param eventDate
     * @return
     *     returns int
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createEvent", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.CreateEvent")
    @ResponseWrapper(localName = "createEventResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.CreateEventResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/createEventRequest", output = "http://webservices.events.folixa.me/IEventsWS/createEventResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/createEvent/Fault/DatabaseException")
    })
    public int createEvent(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "place", targetNamespace = "")
        String place,
        @WebParam(name = "shortDescription", targetNamespace = "")
        String shortDescription,
        @WebParam(name = "longDescription", targetNamespace = "")
        String longDescription,
        @WebParam(name = "categoryId", targetNamespace = "")
        int categoryId,
        @WebParam(name = "eventDate", targetNamespace = "")
        XMLGregorianCalendar eventDate,
        @WebParam(name = "startDate", targetNamespace = "")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        XMLGregorianCalendar endDate,
        @WebParam(name = "validated", targetNamespace = "")
        int validated)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param validated
     * @return
     *     returns java.util.List<me.folixa.ws.events.Event>
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readEventsForAdministrator", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadEventsForAdministrator")
    @ResponseWrapper(localName = "readEventsForAdministratorResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadEventsForAdministratorResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/readEventsForAdministratorRequest", output = "http://webservices.events.folixa.me/IEventsWS/readEventsForAdministratorResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/readEventsForAdministrator/Fault/DatabaseException")
    })
    public List<Event> readEventsForAdministrator(
        @WebParam(name = "validated", targetNamespace = "")
        int validated)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param longDescription
     * @param validated
     * @param endDate
     * @param name
     * @param id
     * @param place
     * @param shortDescription
     * @param categoryId
     * @param startDate
     * @param eventDate
     * @return
     *     returns boolean
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEventById", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.UpdateEventById")
    @ResponseWrapper(localName = "updateEventByIdResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.UpdateEventByIdResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/updateEventByIdRequest", output = "http://webservices.events.folixa.me/IEventsWS/updateEventByIdResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/updateEventById/Fault/DatabaseException")
    })
    public boolean updateEventById(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "place", targetNamespace = "")
        String place,
        @WebParam(name = "shortDescription", targetNamespace = "")
        String shortDescription,
        @WebParam(name = "longDescription", targetNamespace = "")
        String longDescription,
        @WebParam(name = "categoryId", targetNamespace = "")
        int categoryId,
        @WebParam(name = "eventDate", targetNamespace = "")
        XMLGregorianCalendar eventDate,
        @WebParam(name = "startDate", targetNamespace = "")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        XMLGregorianCalendar endDate,
        @WebParam(name = "validated", targetNamespace = "")
        int validated)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteEventById", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.DeleteEventById")
    @ResponseWrapper(localName = "deleteEventByIdResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.DeleteEventByIdResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/deleteEventByIdRequest", output = "http://webservices.events.folixa.me/IEventsWS/deleteEventByIdResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/deleteEventById/Fault/DatabaseException")
    })
    public boolean deleteEventById(
        @WebParam(name = "id", targetNamespace = "")
        int id)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param eventId
     * @return
     *     returns me.folixa.ws.events.Event
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readEventById", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadEventById")
    @ResponseWrapper(localName = "readEventByIdResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadEventByIdResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/readEventByIdRequest", output = "http://webservices.events.folixa.me/IEventsWS/readEventByIdResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/readEventById/Fault/DatabaseException")
    })
    public Event readEventById(
        @WebParam(name = "eventId", targetNamespace = "")
        int eventId)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param categoryId
     * @return
     *     returns java.util.List<me.folixa.ws.events.Event>
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readEventsByCategory", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadEventsByCategory")
    @ResponseWrapper(localName = "readEventsByCategoryResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadEventsByCategoryResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/readEventsByCategoryRequest", output = "http://webservices.events.folixa.me/IEventsWS/readEventsByCategoryResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/readEventsByCategory/Fault/DatabaseException")
    })
    public List<Event> readEventsByCategory(
        @WebParam(name = "categoryId", targetNamespace = "")
        int categoryId)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param place
     * @return
     *     returns java.util.List<me.folixa.ws.events.Event>
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readEventsByPlace", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadEventsByPlace")
    @ResponseWrapper(localName = "readEventsByPlaceResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadEventsByPlaceResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/readEventsByPlaceRequest", output = "http://webservices.events.folixa.me/IEventsWS/readEventsByPlaceResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/readEventsByPlace/Fault/DatabaseException")
    })
    public List<Event> readEventsByPlace(
        @WebParam(name = "place", targetNamespace = "")
        String place)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param endDate
     * @param startDate
     * @return
     *     returns java.util.List<me.folixa.ws.events.Event>
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readEventsBetweenDates", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadEventsBetweenDates")
    @ResponseWrapper(localName = "readEventsBetweenDatesResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadEventsBetweenDatesResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/readEventsBetweenDatesRequest", output = "http://webservices.events.folixa.me/IEventsWS/readEventsBetweenDatesResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/readEventsBetweenDates/Fault/DatabaseException")
    })
    public List<Event> readEventsBetweenDates(
        @WebParam(name = "startDate", targetNamespace = "")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        XMLGregorianCalendar endDate)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param endDate
     * @param text
     * @param place
     * @param categoryId
     * @param startDate
     * @return
     *     returns java.util.List<me.folixa.ws.events.Event>
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readEventsAdvancedSearch", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadEventsAdvancedSearch")
    @ResponseWrapper(localName = "readEventsAdvancedSearchResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadEventsAdvancedSearchResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/readEventsAdvancedSearchRequest", output = "http://webservices.events.folixa.me/IEventsWS/readEventsAdvancedSearchResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/readEventsAdvancedSearch/Fault/DatabaseException")
    })
    public List<Event> readEventsAdvancedSearch(
        @WebParam(name = "text", targetNamespace = "")
        String text,
        @WebParam(name = "categoryId", targetNamespace = "")
        int categoryId,
        @WebParam(name = "place", targetNamespace = "")
        String place,
        @WebParam(name = "startDate", targetNamespace = "")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        XMLGregorianCalendar endDate)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param validated
     * @return
     *     returns java.util.List<me.folixa.ws.events.Event>
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readEventsForUsers", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadEventsForUsers")
    @ResponseWrapper(localName = "readEventsForUsersResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadEventsForUsersResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/readEventsForUsersRequest", output = "http://webservices.events.folixa.me/IEventsWS/readEventsForUsersResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/readEventsForUsers/Fault/DatabaseException")
    })
    public List<Event> readEventsForUsers(
        @WebParam(name = "validated", targetNamespace = "")
        int validated)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param eventsId
     * @return
     *     returns java.util.List<me.folixa.ws.events.Image>
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readImagesByEventId", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadImagesByEventId")
    @ResponseWrapper(localName = "readImagesByEventIdResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadImagesByEventIdResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/readImagesByEventIdRequest", output = "http://webservices.events.folixa.me/IEventsWS/readImagesByEventIdResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/readImagesByEventId/Fault/DatabaseException")
    })
    public List<Image> readImagesByEventId(
        @WebParam(name = "eventsId", targetNamespace = "")
        int eventsId)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param eventsId
     * @param name
     * @param alt
     * @param url
     * @return
     *     returns boolean
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateImageByEventId", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.UpdateImageByEventId")
    @ResponseWrapper(localName = "updateImageByEventIdResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.UpdateImageByEventIdResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/updateImageByEventIdRequest", output = "http://webservices.events.folixa.me/IEventsWS/updateImageByEventIdResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/updateImageByEventId/Fault/DatabaseException")
    })
    public boolean updateImageByEventId(
        @WebParam(name = "eventsId", targetNamespace = "")
        int eventsId,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "url", targetNamespace = "")
        String url,
        @WebParam(name = "alt", targetNamespace = "")
        String alt)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param eventsId
     * @return
     *     returns boolean
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteImagesByEventId", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.DeleteImagesByEventId")
    @ResponseWrapper(localName = "deleteImagesByEventIdResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.DeleteImagesByEventIdResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/deleteImagesByEventIdRequest", output = "http://webservices.events.folixa.me/IEventsWS/deleteImagesByEventIdResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/deleteImagesByEventId/Fault/DatabaseException")
    })
    public boolean deleteImagesByEventId(
        @WebParam(name = "eventsId", targetNamespace = "")
        int eventsId)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteImagesById", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.DeleteImagesById")
    @ResponseWrapper(localName = "deleteImagesByIdResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.DeleteImagesByIdResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/deleteImagesByIdRequest", output = "http://webservices.events.folixa.me/IEventsWS/deleteImagesByIdResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/deleteImagesById/Fault/DatabaseException")
    })
    public boolean deleteImagesById(
        @WebParam(name = "id", targetNamespace = "")
        int id)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param name
     * @return
     *     returns boolean
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCategory", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.CreateCategory")
    @ResponseWrapper(localName = "createCategoryResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.CreateCategoryResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/createCategoryRequest", output = "http://webservices.events.folixa.me/IEventsWS/createCategoryResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/createCategory/Fault/DatabaseException")
    })
    public boolean createCategory(
        @WebParam(name = "name", targetNamespace = "")
        String name)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<me.folixa.ws.events.EventsCategories>
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readAllCategories", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadAllCategories")
    @ResponseWrapper(localName = "readAllCategoriesResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.ReadAllCategoriesResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/readAllCategoriesRequest", output = "http://webservices.events.folixa.me/IEventsWS/readAllCategoriesResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/readAllCategories/Fault/DatabaseException")
    })
    public List<EventsCategories> readAllCategories()
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param name
     * @param id
     * @return
     *     returns boolean
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCategoryById", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.UpdateCategoryById")
    @ResponseWrapper(localName = "updateCategoryByIdResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.UpdateCategoryByIdResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/updateCategoryByIdRequest", output = "http://webservices.events.folixa.me/IEventsWS/updateCategoryByIdResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/updateCategoryById/Fault/DatabaseException")
    })
    public boolean updateCategoryById(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "name", targetNamespace = "")
        String name)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCategoryById", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.DeleteCategoryById")
    @ResponseWrapper(localName = "deleteCategoryByIdResponse", targetNamespace = "http://webservices.events.folixa.me/", className = "me.folixa.ws.events.DeleteCategoryByIdResponse")
    @Action(input = "http://webservices.events.folixa.me/IEventsWS/deleteCategoryByIdRequest", output = "http://webservices.events.folixa.me/IEventsWS/deleteCategoryByIdResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://webservices.events.folixa.me/IEventsWS/deleteCategoryById/Fault/DatabaseException")
    })
    public boolean deleteCategoryById(
        @WebParam(name = "id", targetNamespace = "")
        int id)
        throws DatabaseException_Exception
    ;

}
