
package me.folixa.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EventsWSService", targetNamespace = "http://webservices.events.folixame.ws/", wsdlLocation = "http://156.35.95.51:8080/wsfolixameevents/events?wsdl")
public class EventsWSService
    extends Service
{

    private final static URL EVENTSWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException EVENTSWSSERVICE_EXCEPTION;
    private final static QName EVENTSWSSERVICE_QNAME = new QName("http://webservices.events.folixame.ws/", "EventsWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://156.35.95.51:8080/wsfolixameevents/events?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EVENTSWSSERVICE_WSDL_LOCATION = url;
        EVENTSWSSERVICE_EXCEPTION = e;
    }

    public EventsWSService() {
        super(__getWsdlLocation(), EVENTSWSSERVICE_QNAME);
    }

    public EventsWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EVENTSWSSERVICE_QNAME, features);
    }

    public EventsWSService(URL wsdlLocation) {
        super(wsdlLocation, EVENTSWSSERVICE_QNAME);
    }

    public EventsWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EVENTSWSSERVICE_QNAME, features);
    }

    public EventsWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EventsWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEventsWS
     */
    @WebEndpoint(name = "EventsWSPort")
    public IEventsWS getEventsWSPort() {
        return super.getPort(new QName("http://webservices.events.folixame.ws/", "EventsWSPort"), IEventsWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEventsWS
     */
    @WebEndpoint(name = "EventsWSPort")
    public IEventsWS getEventsWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.events.folixame.ws/", "EventsWSPort"), IEventsWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EVENTSWSSERVICE_EXCEPTION!= null) {
            throw EVENTSWSSERVICE_EXCEPTION;
        }
        return EVENTSWSSERVICE_WSDL_LOCATION;
    }

}
