
package me.folixa.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UsersSoap", targetNamespace = "http://folixa.me/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsersSoap {


    /**
     * 
     * @param password
     * @param email
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SignUp", action = "http://folixa.me/SignUp")
    @WebResult(name = "SignUpResult", targetNamespace = "http://folixa.me/")
    @RequestWrapper(localName = "SignUp", targetNamespace = "http://folixa.me/", className = "ws.unit6.example1.webservice.SignUp")
    @ResponseWrapper(localName = "SignUpResponse", targetNamespace = "http://folixa.me/", className = "ws.unit6.example1.webservice.SignUpResponse")
    public String signUp(
        @WebParam(name = "email", targetNamespace = "http://folixa.me/")
        String email,
        @WebParam(name = "password", targetNamespace = "http://folixa.me/")
        String password);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LogIn", action = "http://folixa.me/LogIn")
    @WebResult(name = "LogInResult", targetNamespace = "http://folixa.me/")
    @RequestWrapper(localName = "LogIn", targetNamespace = "http://folixa.me/", className = "ws.unit6.example1.webservice.LogIn")
    @ResponseWrapper(localName = "LogInResponse", targetNamespace = "http://folixa.me/", className = "ws.unit6.example1.webservice.LogInResponse")
    public String logIn();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Delete", action = "http://folixa.me/Delete")
    @WebResult(name = "DeleteResult", targetNamespace = "http://folixa.me/")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://folixa.me/", className = "ws.unit6.example1.webservice.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://folixa.me/", className = "ws.unit6.example1.webservice.DeleteResponse")
    public String delete();

    /**
     * 
     * @param inputEmail
     * @param inputPassword
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Update", action = "http://folixa.me/Update")
    @WebResult(name = "UpdateResult", targetNamespace = "http://folixa.me/")
    @RequestWrapper(localName = "Update", targetNamespace = "http://folixa.me/", className = "ws.unit6.example1.webservice.Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://folixa.me/", className = "ws.unit6.example1.webservice.UpdateResponse")
    public String update(
        @WebParam(name = "inputEmail", targetNamespace = "http://folixa.me/")
        String inputEmail,
        @WebParam(name = "inputPassword", targetNamespace = "http://folixa.me/")
        String inputPassword);

    /**
     * 
     * @return
     *     returns ws.unit6.example1.webservice.ArrayOfProfile
     */
    @WebMethod(operationName = "GetProfiles", action = "http://folixa.me/GetProfiles")
    @WebResult(name = "GetProfilesResult", targetNamespace = "http://folixa.me/")
    @RequestWrapper(localName = "GetProfiles", targetNamespace = "http://folixa.me/", className = "ws.unit6.example1.webservice.GetProfiles")
    @ResponseWrapper(localName = "GetProfilesResponse", targetNamespace = "http://folixa.me/", className = "ws.unit6.example1.webservice.GetProfilesResponse")
    public ArrayOfProfile getProfiles();

}
